### ISSUE TITLE
Device ID isn't updated after calling useAdvertisingIdForDeviceId

### ISSUE THREAD

**Issue by chestnut-wm** [amplitude/Amplitude-iOS#197]
We are using the Amplitude SDK (4.3.1) and want to migrate to using the IDFA as the DeviceID.

Calling `useAdvertisingIdForDeviceId()` right before initializing the SDK though we aren't seeing the IDFA listed as DeviceID. 

I added the following validation check

```
let idfa = ASIdentifierManager.shared().advertisingIdentifier.uuidString
let ampID = Amplitude.instance()?.getDeviceId() ?? ""
if idfa == ampID {
    print("Matches")
} else {
    print("Doesn't Match")
}
```

The two IDs don't match if the app had previously set up the SDK without the `useAdvertisingIdForDeviceId` call. But If I delete the app and reinstall fresh the two IDs match. It seems like the deviceID is just never being updated if it already has a previous value.

I couldn't find any open issue or documentation around this use case, and the issue doesn't seem to be reproducible with the Android SDK. Is this a known issue or expected behavior? Any feedback would be appreciated.

**Comment by haoliu-amp** [comment]
Hey,

You can explicitly call `- (void)setDeviceId:(NSString*) deviceId;` after you get IDFA back.

However, here are what could happen.

1. If you do set userId, setting a different deviceId is fine. They will still be identified as the same user.
2. If userId is not set, user will be identified as a new user, since the deviceId is changed.
