### ISSUE TITLE
what is amplitude_attribution_ids key in export payload after sending data using the iOS SDK

### ISSUE THREAD

**Issue by sayan-mitra** [amplitude/Amplitude-iOS#341]
## Summary

After sending data to Amplitude using the iOS SDK, when I export the payload using the export API, I see a key **amplitude_attribution_ids**  in the payload which has an array value. What it is and how is this populated by Amplitude.
I looked at the attribution API for some reference, but the export payload doesn't have the **idfa value and is set to null**. 
Is the iOS SDK sending attribution data too ?

Any reference or understanding will really help. Thanks!

**Comment by haoliu-amp** [comment]
@sayan-mitra In our SDK, idfa will be collected only if you enable it and pass your idfa collection logic. Regarding the `amplitude_attribution_ids` for the export API, you can go to [Amplitude Help](https://help.amplitude.com/hc/en-us/requests/new) to file a question since it's owned by another team.

Thanks! Closing this since it's mainly for export API but not SDK.
